services:
  mongo:
    image: mongo:5.0
    networks:
      - app_network
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
  express:
    build:
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
    networks:
      - app_network
    container_name: express-dev
    ports:
      - "8000:8000"
networks:
  app_network:
    driver: bridge