version: '3.8'

services:
  mongo:
    networks:
      - app_network
    build:
      context: .
      dockerfile: mongoDockerfile
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/dump/mongo-init-dump:/docker-entrypoint-initdb.d/dump
    restart: unless-stopped
  express:
    networks:
      - app_network
    build:
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/usr/src/app
    container_name: express
    ports:
      - "8000:8000"
networks:
  app_network:
    driver: bridge